export const AUTHENTICATE_DATA = 'AUTHENTICATE_DATA';
export const CREATE_DATA = 'CREATE_DATA';
export const TOGGLE_SPLASH = 'TOGGLE_SPLASH';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
